### ISSUE TITLE
build fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by funkyfuture** [dropbox/pyston#1261]
i can successfully build a Docker image with this `Dockerfile`:

```
FROM ubuntu:trusty

ENV PYSTON_VERSION=0.5.0
RUN build_deps="automake git cmake ninja-build ccache liblzma-dev libgmp3-dev libmpfr-dev autoconf libtool python-dev texlive-extra-utils clang pkg-config libbz2-dev time libncurses5-dev libreadline-dev libsqlite3-dev libssl-dev zlib1g-dev" \
 && apt-get -q update \
 && DEBIAN_FRONTEND=noninteractive apt-get -qy install $build_deps \
 && cd /root \
 && git config --global user.name "nest-of-serpents" \
 && git config --global user.email "funkyfuture+nest-of-serpents@hub.docker.com" \
 && git clone https://github.com/dropbox/pyston.git \
 && git clone https://github.com/llvm-mirror/llvm.git pyston_deps/llvm-trunk \
 && git clone https://github.com/llvm-mirror/clang.git pyston_deps/llvm-trunk/tools/clang \
 && cd pyston \
 && git checkout v${PYSTON_VERSION} \
 && git submodule update --init --recursive build_deps \
 && make llvm_up && make && make pyston_release \
 && rm -rf .git* .travis.yml .vimrc.dir \
 && cd .. && mv pyston /opt && rm -R pyston_deps \
 && cd /opt/pyston && ln -s pyston* /usr/local/bin && ln -s pyston_release /usr/local/bin/pyston \
 && DEBIAN_FRONTEND=noninteractive apt-get -yq --purge autoremove $build_deps \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
```

however it fails, if i base the image on `ubuntu:xenial` with the following output:
```
[3389/3459] Building CXX object src/CMakeFiles/PYSTON_OBJECTS.dir/runtime/cxx_unwind.cpp.o
FAILED: CCACHE_CPP2=yes /usr/bin/ccache /usr/bin/clang++   -DDEFAULT_PYTHON_MAJOR_VERSION=2 -DDEFAULT_PYTHON_MICRO_VERSION=6 -DDEFAULT_PYTHON_MINOR_VERSION=7 -DLLVMREV=230300 -DNVALGRIND -DPYMALLOC_DEBUG -DPy_REF_DEBUG -DPy_TRACE_REFS -DTHREADING_USE_GIL=1 -DTHREADING_USE_GRWL=0 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -Isrc -I../../src -Ifrom_cpython/Include -I/root/pyston_deps/llvm-trunk/include -Illvm/include -I. -Ibuild_deps/libunwind/include -I../../build_deps/libpypa/src -I../../build_deps/lz4/lib -Qunused-arguments -fcolor-diagnostics  -Qunused-arguments -fcolor-diagnostics -Wall -Wextra -Werror -Wreturn-type -Wno-sign-compare -Wno-unused -Wno-unused-parameter -fno-omit-frame-pointer -g -std=c++11 -fno-rtti -fexceptions -fvisibility-inlines-hidden -ffunction-sections -fdata-sections -Woverloaded-virtual -Wno-invalid-offsetof -Wcast-qual -Wno-sign-conversion -Wnon-virtual-dtor -Winit-self -Wmissing-include-dirs -Wstrict-overflow=5 -Wpointer-arith -Wtype-limits -Wwrite-strings -Wempty-body -Waggregate-return -Wmissing-field-initializers -Wredundant-decls -Winline -Wint-to-pointer-cast -Wlong-long -Wvla -Wno-attributes -g -Qunused-arguments -fcolor-diagnostics -Wimplicit-int -Wstrict-prototypes -Wold-style-definition -Wnested-externs -Wpointer-to-int-cast -Wno-mismatched-tags -Wno-extern-c-compat   -g -DBINARY_SUFFIX= -DBINARY_STRIPPED_SUFFIX=_stripped -DPy_BUILD_CORE -D_PYSTON_API -MMD -MT src/CMakeFiles/PYSTON_OBJECTS.dir/runtime/builtin_modules/builtins.cpp.o -MF src/CMakeFiles/PYSTON_OBJECTS.dir/runtime/builtin_modules/builtins.cpp.o.d -o src/CMakeFiles/PYSTON_OBJECTS.dir/runtime/builtin_modules/builtins.cpp.o -c ../../src/runtime/builtin_modules/builtins.cpp
../../src/runtime/builtin_modules/builtins.cpp:1238:29: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
        iterators.push_back(std::move(range.begin()));
                            ^
../../src/runtime/builtin_modules/builtins.cpp:1238:29: note: remove std::move call here
        iterators.push_back(std::move(range.begin()));
                            ^~~~~~~~~~             ~
1 error generated.
FAILED: CCACHE_CPP2=yes /usr/bin/ccache /usr/bin/clang++   -DDEFAULT_PYTHON_MAJOR_VERSION=2 -DDEFAULT_PYTHON_MICRO_VERSION=6 -DDEFAULT_PYTHON_MINOR_VERSION=7 -DLLVMREV=230300 -DNVALGRIND -DPYMALLOC_DEBUG -DPy_REF_DEBUG -DPy_TRACE_REFS -DTHREADING_USE_GIL=1 -DTHREADING_USE_GRWL=0 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -Isrc -I../../src -Ifrom_cpython/Include -I/root/pyston_deps/llvm-trunk/include -Illvm/include -I. -Ibuild_deps/libunwind/include -I../../build_deps/libpypa/src -I../../build_deps/lz4/lib -Qunused-arguments -fcolor-diagnostics  -Qunused-arguments -fcolor-diagnostics -Wall -Wextra -Werror -Wreturn-type -Wno-sign-compare -Wno-unused -Wno-unused-parameter -fno-omit-frame-pointer -g -std=c++11 -fno-rtti -fexceptions -fvisibility-inlines-hidden -ffunction-sections -fdata-sections -Woverloaded-virtual -Wno-invalid-offsetof -Wcast-qual -Wno-sign-conversion -Wnon-virtual-dtor -Winit-self -Wmissing-include-dirs -Wstrict-overflow=5 -Wpointer-arith -Wtype-limits -Wwrite-strings -Wempty-body -Waggregate-return -Wmissing-field-initializers -Wredundant-decls -Winline -Wint-to-pointer-cast -Wlong-long -Wvla -Wno-attributes -g -Qunused-arguments -fcolor-diagnostics -Wimplicit-int -Wstrict-prototypes -Wold-style-definition -Wnested-externs -Wpointer-to-int-cast -Wno-mismatched-tags -Wno-extern-c-compat   -g -DBINARY_SUFFIX= -DBINARY_STRIPPED_SUFFIX=_stripped -DPy_BUILD_CORE -D_PYSTON_API -MMD -MT src/CMakeFiles/PYSTON_OBJECTS.dir/runtime/capi.cpp.o -MF src/CMakeFiles/PYSTON_OBJECTS.dir/runtime/capi.cpp.o.d -o src/CMakeFiles/PYSTON_OBJECTS.dir/runtime/capi.cpp.o -c ../../src/runtime/capi.cpp
../../src/runtime/capi.cpp:513:13: error: use of undeclared identifier 'isinf'
        if (Py_IS_INFINITY(v))
            ^
from_cpython/Include/pymath.h:121:31: note: expanded from macro 'Py_IS_INFINITY'
#    define Py_IS_INFINITY(X) isinf(X)
                              ^
1 error generated.
ninja: build stopped: subcommand failed.
```

**Comment by undingen** [comment]
Unfortunately pyston 0.5 does not build on 16.04 like you have been running into. :-(
We fixed the build on master though, so you will have to directly checkout master (or wait until we released 0.5.1 (probably in 1-2 weeks??))

**Comment by funkyfuture** [comment]
ai'ght, thanks for the quick response. i'll wait. i'd like to keep this issue open as a reminder, but it may also be closed.
